### PR TITLE
Added OVER (PARTITION BY) clause

### PR DESCRIPTION
**Pull request by MichaelBlume**
Duplicate of #28 less merge conflicts

### CODE REVIEW

**Comment by MichaelBlume** [comment]
Still needs tests

**Comment by MichaelBlume** [comment]
@Menthalion @ddellacosta I've been meaning to add tests to this so it can be merged and haven't gotten to it. If either of you are feeling enthused about adding some tests and getting this merged, go for it.

**Comment by ddellacosta** [comment]
@MichaelBlume Hey, sorry I've been slow to respond lately--will take a look and get in some tests if i can!

**Comment by seancorfield** [comment]
@ddellacosta @Menthalion Interested in adding tests?

**Comment by seancorfield** [comment]
Closing this for want of tests and no takers.

**Comment by Menthalion** [comment]
Yeah, sorry Sean but since I never grokked the right way to create / extend 
HoneySQL clauses I wasn't really sure about this code

**Pull request closed without merging**
