### PR TITLE
Add minimal testing for #288

### PR DESCRIPTION
**Pull request by arichiardi**
I actually got some trouble with that commit so I am adding some testing here
and with time trying to understand the issue better.

### CODE REVIEW

**Comment by seancorfield** [comment]
That test is bogus. You were trying to `(apply merge-where ...)` with no arguments. In the tests, you are calling `(merge-where … [])` which is definitely illegal and that's why the tests are failing with NPE.

**Comment by seancorfield** [comment]
I assume you mean #228, not #288 by the way?

**Comment by arichiardi** [comment]
Ah right, aren't the other two worth including though? I was coding at night so maybe I misinterpreted :smile:

Why closing the PR? It seems to me you are a bit too quick at closing things. At the end of the day I am trying to help no?

**Comment by arichiardi** [comment]
I can open a new one with the correct number of the issue.

**Pull request closed without merging**
