### PR TITLE
Add support for MySQL REPLACE INTO

### PR DESCRIPTION
**Pull request by delenius**
This adds support for MySQL's "REPLACE INTO" syntax.
See: https://dev.mysql.com/doc/refman/5.5/en/replace.html

### CODE REVIEW

**Comment by seancorfield** [comment]
`REPLACE INTO` is non-standard (MySQL-specific) so it does not belong in HoneySQL. You can use HoneySQL's extension points to add it in your own code.

Note: there is a PostgreSQL-specific library of extensions to HoneySQL so this might be a good time to create a MySQL-specifci library and start out with adding `REPLACE INTO` that way.

**Comment by delenius** [comment]
I tried that, but the problem I ran into was that I couldn't change `honeysql.format/default-clause-priorities`, so my "REPLACE INTO" ended up at the end of the SQL string. Is there a way around this?

**Comment by seancorfield** [comment]
Use `honeysql.format/register-clause!` to add priorities for new clauses.

**Comment by delenius** [comment]
Ah, yes, just found that :) That works, thanks.

**Comment by seancorfield** [comment]
I've updated the README to include `register-clause!` (in the Extensibility section).

**Comment by seancorfield** [comment]
(oops, typo'd the issue number in that commit message!)

**Pull request closed without merging**
