### PR TITLE
adds support for JOIN ... USING (...) syntax (#188)

### PR DESCRIPTION
**Pull request by vincent-dm**
Implements #188

### CODE REVIEW

**Comment by vincent-dm** [comment]
@MichaelBlume any idea when you will cut the next release so I can start using this? Thanks!

**Comment by MichaelBlume** [comment]
I'll try to cut a release this evening.

**Comment by vincent-dm** [comment]
great, thanks Michael!

**Comment by vincent-dm** [comment]
@MichaelBlume any idea about ETA? Thanks!

**Pull request merged**
