### PR TITLE
Adds :enable-values-subqueries? option to honeysql.format/format

### PR DESCRIPTION
**Pull request by emidln**
When :enable-values-subqueries? is set to false, treat maps provided
in a :values clause as a parameter instead of as a subquery. By default,
:enable-values-subqueries? is true, retaining existing behavior.

This allows handling IPersistentMaps at the jdbc level. Vectors could 
probably also use this treatment, but that can be for another pull request.

### CODE REVIEW

**Comment by MichaelBlume** [comment]
Yep, looks good to me. @jkk @ddellacosta ?

**Comment by MichaelBlume** [comment]
As an alternative what if we did something like https://github.com/MichaelBlume/honeysql/commit/value and expected the user to wrap the map value in a call to value?

**Comment by emidln** [comment]
I'd be all for fewer dynamic bindings. It was a bit rough wading into this file...

**Comment by emidln** [comment]
As a nice bonus, value would let us handle misc other types if we wanted (e.g. Vector to turn into an org.postgresql.jdbc.Jdbc4Array).

**Comment by emidln** [comment]
Withdrawing this in favor of https://github.com/jkk/honeysql/pull/65.

**Pull request closed without merging**
