### PR TITLE
Support for `RETURNING` keyword

### PR DESCRIPTION
**Pull request by erikprice**
PostgreSQL supports this clause on INSERT statements so as to return things such as generated IDs, etc.

### CODE REVIEW

**Comment by erikprice** [comment]
Updated to remove redundant `defmethod` per comment from @MichaelBlume .

**Comment by ddellacosta** [comment]
I'm on the fence about this one, but I think it would be good to try to keep HoneySQL limited to ANSI SQL at this point--allowing in vendor-specific syntax could be a slippery slope, and ideally I think HoneySQL should simply make it easy to extend it when one has to support a vendor-specific bit of syntax.  Related: would #42 allow for this one to be provided as an extension?

**Comment by MichaelBlume** [comment]
Yeah, that's pretty much exactly what I was thinking, I'd rather keep
vendor-specific syntax out of the core lib. And yes, with #43 merged this
basically becomes an extension.

One thing I could *maybe* see doing is having, say, a honeysql.postgresql
ns that could be required separately and include postgres-specific syntax,
but I'd also be happy simply limiting the library to ANSI SQL.

**Comment by MichaelBlume** [comment]
Ha, didn't see your edit, but we seem to be on the same wavelength @ddellacosta =)

**Comment by ddellacosta** [comment]
Yes!

**Comment by MichaelBlume** [comment]
Yeah, I'm going to go ahead and close this one for now. Note again that with v0.5.0 this will be very easy to add from your own project.

**Pull request closed without merging**
