### PR TITLE
Remove nil argument to where

### PR DESCRIPTION
**Pull request by visibletrap**
Try to addresses #203

### CODE REVIEW

**Comment by MichaelBlume** [comment]
I've already merged this but if you wanted to submit another PR with a test case I'd appreciate it a lot and merge it right away.

**Comment by visibletrap** [comment]
Thanks.

I need a your guide for a bit. What type of test do you prefer, a function focused test or high-level test? Should I add to `core_test.cljc` or create a `helpers_test.cljc`? Any test that you like which I could use as an example?

**Comment by MichaelBlume** [comment]
I think something in format_test would be fine -- your example in #203 would make a good test case.

**Comment by visibletrap** [comment]
First of all, I'm not the one requesting for this change. Just a random person pass by and found this easy enough for me to get started.

Second, I created a PR adding a test. But after seeing test examples in `format_test`, I kind of change my mind about the implementation that got merged. I'm not sure you would agree with me. And I don't want to trouble you too much so I present both options for you. Please choose to merge one of these and just close the other.

* #205 New implementation and its test (I prefer)
* #206 Only test for the current implementation

**Comment by MichaelBlume** [comment]
Got it, thanks ^_^

**Pull request merged**
